// <auto-generated />
using System;
using EBR.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EBR.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EbrDbContext))]
    [Migration("20260909220252_AddCaseAssignment")]
    partial class AddCaseAssignment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EBR.Domain.Companies.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("direccion");

                    b.Property<string>("EconomicActivity")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("actividad_economica");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("correo");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("municipio");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("provincia");

                    b.Property<string>("Rnc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rnc");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_comercial");

                    b.Property<Guid>("VersionToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version_token");

                    b.HasKey("Id");

                    b.HasIndex("Rnc")
                        .IsUnique();

                    b.ToTable("Empresa", (string)null);
                });

            modelBuilder.Entity("EBR.Domain.Companies.CompanyHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cambio");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cambiado_por");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cambios");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("CompanyId", "ChangedAt");

                    b.ToTable("Empresa_Historial", (string)null);
                });

            modelBuilder.Entity("EBR.Domain.Companies.CompanyRepresentative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("correo");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_completo");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("vigente");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.Property<string>("RepresentativeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_representante");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "DocumentNumber")
                        .IsUnique();

                    b.HasIndex("CompanyId", "RepresentativeType")
                        .IsUnique()
                        .HasDatabaseName("IX_Representante_Empresa_empresa_id_tipo_representante_vigente")
                        .HasFilter("vigente");

                    b.ToTable("Representante_Empresa", null, t =>
                        {
                            t.HasCheckConstraint("CK_Representante_Tipo", "tipo_representante IN ('LEGAL','CALIDAD','CONTACTO_PRINCIPAL')");
                        });
                });

            modelBuilder.Entity("EBR.Domain.Companies.CompanyUser", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("CompanyId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Empresa_Usuario", (string)null);
                });

            modelBuilder.Entity("EBR.Domain.Evaluations.EvaluationGuidanceCriterion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("Criticality")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("criticidad");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("SourceCell")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("celda_origen");

                    b.Property<string>("SourceSheet")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("hoja_origen");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "Code")
                        .IsUnique();

                    b.ToTable("Plantilla_Evaluacion_Criterio", null, t =>
                        {
                            t.HasCheckConstraint("CK_Criterio_Criticidad", "criticidad IS NULL OR criticidad IN ('CRITICAL','MAJOR','MINOR')");
                        });
                });

            modelBuilder.Entity("EBR.Domain.Evaluations.EvaluationImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_contenido");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("text")
                        .HasColumnName("detalle_error");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("archivo");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("hoja");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("estado");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("plantilla_id");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("FileName", "SheetName", "ContentHash")
                        .IsUnique();

                    b.ToTable("Plantilla_Importacion_Lote", null, t =>
                        {
                            t.HasCheckConstraint("CK_Lote_Estado", "estado IN ('PENDIENTE','PROMOVIDO','RECHAZADO')");
                        });
                });

            modelBuilder.Entity("EBR.Domain.Evaluations.EvaluationImportRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("integer")
                        .HasColumnName("lote_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("text")
                        .HasColumnName("detalle_error");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_item");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_padre");

                    b.Property<string>("SourceCell")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("celda_origen");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("estado");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "Code")
                        .IsUnique();

                    b.ToTable("Plantilla_Importacion_Fila", null, t =>
                        {
                            t.HasCheckConstraint("CK_Fila_Estado", "estado IN ('PENDIENTE','PROMOVIDO','RECHAZADO')");
                        });
                });

            modelBuilder.Entity("EBR.Domain.Evaluations.EvaluationQualificationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accion");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clasificacion");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("MaxIncluded")
                        .HasColumnType("boolean")
                        .HasColumnName("maximo_incluido");

                    b.Property<decimal?>("MaxPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_max");

                    b.Property<bool>("MinIncluded")
                        .HasColumnType("boolean")
                        .HasColumnName("minimo_incluido");

                    b.Property<decimal?>("MinPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_min");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("plantilla_id");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "Code")
                        .IsUnique();

                    b.ToTable("Plantilla_Evaluacion_Regla", null, t =>
                        {
                            t.HasCheckConstraint("CK_Regla_Calificacion", "porcentaje_min IS NOT NULL OR porcentaje_max IS NOT NULL");
                        });
                });

            modelBuilder.Entity("EBR.Domain.Evaluations.EvaluationResponseOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("codigo");

                    b.Property<bool>("CountsTowardDenominator")
                        .HasColumnType("boolean")
                        .HasColumnName("cuenta_denominador");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("plantilla_id");

                    b.Property<decimal?>("Value")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "Code")
                        .IsUnique();

                    b.ToTable("Plantilla_Evaluacion_Opcion", null, t =>
                        {
                            t.HasCheckConstraint("CK_Opcion_Evaluable", "(valor IS NULL AND NOT cuenta_denominador) OR (valor IS NOT NULL AND cuenta_denominador AND valor BETWEEN 0 AND 1)");
                        });
                });

            modelBuilder.Entity("EBR.Domain.Evaluations.EvaluationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("familia_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_publicacion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId", "Version")
                        .IsUnique();

                    b.ToTable("Plantilla_Evaluacion", (string)null);
                });

            modelBuilder.Entity("EBR.Domain.Evaluations.EvaluationTemplateItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowsNotApplicable")
                        .HasColumnType("boolean")
                        .HasColumnName("permite_no_aplica");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean")
                        .HasColumnName("critico");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("requerido");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_item");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("padre_id");

                    b.Property<string>("ResponseType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_respuesta");

                    b.Property<string>("RulesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reglas");

                    b.Property<string>("ScoreConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuracion_puntaje");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("plantilla_id");

                    b.Property<Guid>("VersionToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version_token");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)")
                        .HasColumnName("peso");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("TemplateId", "Code")
                        .IsUnique();

                    b.HasIndex("TemplateId", "ParentId", "Order");

                    b.ToTable("Plantilla_Evaluacion_Item", (string)null);
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.CompanyFoodSubcategory", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("subcategoria_id");

                    b.HasKey("CompanyId", "SubcategoryId");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Establecimiento_Subcategoria", (string)null);
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.CompanyRiskFactorValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<int>("FactorId")
                        .HasColumnType("integer")
                        .HasColumnName("factor_id");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("vigente");

                    b.Property<int>("OptionId")
                        .HasColumnType("integer")
                        .HasColumnName("opcion_id");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<Guid>("RegisteredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("registrado_por");

                    b.HasKey("Id");

                    b.HasIndex("FactorId");

                    b.HasIndex("OptionId");

                    b.HasIndex("RegisteredBy");

                    b.HasIndex("CompanyId", "FactorId", "IsCurrent");

                    b.ToTable("Establecimiento_Factor_Valor", (string)null);
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.FoodCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categoria_Alimento", (string)null);
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.FoodSubcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<int?>("ChemicalRiskLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("riesgo_quimi_id");

                    b.Property<decimal?>("ChemicalScore")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("puntaje_quimico");

                    b.Property<int?>("MicrobiologicalRiskLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("riesgo_micro_id");

                    b.Property<decimal?>("MicrobiologicalScore")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("puntaje_micro");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int?>("TotalRiskLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_riesgo_total");

                    b.Property<decimal?>("TotalScore")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("puntaje_total");

                    b.HasKey("Id");

                    b.HasIndex("ChemicalRiskLevelId");

                    b.HasIndex("MicrobiologicalRiskLevelId");

                    b.HasIndex("TotalRiskLevelId");

                    b.HasIndex("CategoryId", "Name")
                        .IsUnique();

                    b.ToTable("Subcategoria_Alimento", (string)null);
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.FoodSubcategoryHazard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HazardType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_peligro");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_escala_id");

                    b.Property<decimal?>("ScoreOverride")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("puntaje_propio");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("subcategoria_id");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("SubcategoryId", "HazardType")
                        .IsUnique();

                    b.ToTable("Subcategoria_Alimento_Peligro", null, t =>
                        {
                            t.HasCheckConstraint("CK_Peligro_Valido", "tipo_peligro IN ('MICROBIOLOGICAL','CHEMICAL') AND (puntaje_propio IS NULL OR puntaje_propio > 0)");
                        });
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.InspectionFrequencyMatrix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FrequencyMonths")
                        .HasColumnType("integer")
                        .HasColumnName("frecuencia_meses");

                    b.Property<bool>("MinimumIncluded")
                        .HasColumnType("boolean")
                        .HasColumnName("riesgo_min_incluido");

                    b.Property<int>("RiskLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_riesgo_id");

                    b.Property<decimal>("RiskMax")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("riesgo_max");

                    b.Property<decimal>("RiskMin")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("riesgo_min");

                    b.Property<int?>("RuleVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("version_regla_id");

                    b.Property<int?>("ScaleLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_escala_id");

                    b.HasKey("Id");

                    b.HasIndex("RiskLevelId");

                    b.HasIndex("RuleVersionId");

                    b.HasIndex("ScaleLevelId");

                    b.ToTable("Matriz_Frecuencia_Inspeccion", (string)null);
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.RiskCalculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_calculo");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<decimal>("EstablishmentRisk")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("riesgo_establecimiento_re");

                    b.Property<string>("FactorDetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle_factores");

                    b.Property<Guid>("GeneratedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("generado_por");

                    b.Property<int>("InspectionFrequencyMatrixId")
                        .HasColumnType("integer")
                        .HasColumnName("matriz_frecuencia_id");

                    b.Property<decimal>("ProductRisk")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("riesgo_producto_rd");

                    b.Property<int>("RiskLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_riesgo_id");

                    b.Property<int?>("RuleVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("version_regla_id");

                    b.Property<decimal>("TotalRisk")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("riesgo_total_rt");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedBy");

                    b.HasIndex("InspectionFrequencyMatrixId");

                    b.HasIndex("RiskLevelId");

                    b.HasIndex("RuleVersionId");

                    b.HasIndex("CompanyId", "CalculatedAt");

                    b.ToTable("Calculo_Riesgo", (string)null);
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.RiskLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("puntos");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Points")
                        .IsUnique();

                    b.ToTable("Nivel_Riesgo", (string)null);
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.RiskRuleVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AggregationMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("metodo_agregacion");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigente_desde");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigente_hasta");

                    b.Property<int>("FrequencyScaleId")
                        .HasColumnType("integer")
                        .HasColumnName("escala_frecuencia_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("publicado");

                    b.Property<int>("ProductScaleId")
                        .HasColumnType("integer")
                        .HasColumnName("escala_producto_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("FrequencyScaleId");

                    b.HasIndex("ProductScaleId");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("Version_Regla_Riesgo", null, t =>
                        {
                            t.HasCheckConstraint("CK_Regla_Valida", "metodo_agregacion = 'MAX' AND (vigente_hasta IS NULL OR vigente_hasta > vigente_desde)");
                        });
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.RiskScale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigente_desde");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigente_hasta");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Code", "Version")
                        .IsUnique();

                    b.ToTable("Escala_Riesgo", null, t =>
                        {
                            t.HasCheckConstraint("CK_Escala_Vigencia", "vigente_hasta IS NULL OR vigente_hasta > vigente_desde");
                        });
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.RiskScaleLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("ScaleId")
                        .HasColumnType("integer")
                        .HasColumnName("escala_id");

                    b.Property<decimal>("Score")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("puntaje");

                    b.HasKey("Id");

                    b.HasIndex("ScaleId", "Code")
                        .IsUnique();

                    b.HasIndex("ScaleId", "Rank")
                        .IsUnique();

                    b.ToTable("Escala_Riesgo_Nivel", null, t =>
                        {
                            t.HasCheckConstraint("CK_Nivel_Valido", "codigo IN ('LOW','MEDIUM','HIGH') AND puntaje > 0 AND orden BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.StructuralRiskFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nombre");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int?>("RuleVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("version_regla_id");

                    b.Property<decimal>("Weight")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("peso");

                    b.HasKey("Id");

                    b.HasIndex("RuleVersionId", "Code")
                        .IsUnique();

                    b.ToTable("Factor_Riesgo_Establecimiento", (string)null);
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.StructuralRiskOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<int>("FactorId")
                        .HasColumnType("integer")
                        .HasColumnName("factor_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<decimal>("Score")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("puntaje");

                    b.HasKey("Id");

                    b.HasIndex("FactorId", "Order")
                        .IsUnique();

                    b.ToTable("Factor_Riesgo_Opcion", (string)null);
                });

            modelBuilder.Entity("EBR.Domain.Workflow.BpmRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por");

                    b.Property<string>("EstablishmentType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("tipo_establecimiento");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("observaciones");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_envio");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<Guid>("VersionToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version_token");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CompanyId", "Status", "CreatedAt");

                    b.ToTable("Solicitud_BPM", (string)null);
                });

            modelBuilder.Entity("EBR.Domain.Workflow.BpmRequestDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BpmRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("solicitud_id");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tipo_documento");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("hash");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tipo_mime");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("StorageReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("referencia_almacenamiento");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_carga");

                    b.HasKey("Id");

                    b.HasIndex("BpmRequestId", "UploadedAt");

                    b.ToTable("Solicitud_BPM_Documento", (string)null);
                });

            modelBuilder.Entity("EBR.Domain.Workflow.CaseAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asignacion");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("asignado_por");

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("caso_id");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("vigente");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("motivo");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid")
                        .HasColumnName("tecnico_id");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("CaseId")
                        .IsUnique()
                        .HasDatabaseName("IX_Caso_Asignacion_caso_id_vigente")
                        .HasFilter("vigente");

                    b.HasIndex("TechnicianId");

                    b.HasIndex("CaseId", "AssignedAt");

                    b.ToTable("Caso_Asignacion", (string)null);
                });

            modelBuilder.Entity("EBR.Domain.Workflow.CaseStateHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("caso_id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cambio");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cambiado_por");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado_nuevo");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado_anterior");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("motivo");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("CaseId", "ChangedAt");

                    b.ToTable("Caso_Estado_Historial", (string)null);
                });

            modelBuilder.Entity("EBR.Domain.Workflow.Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Complainant")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("denunciante");

                    b.Property<string>("ComplaintType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tipo_denuncia");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_decision");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("motivo_decision");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("descripcion");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_recepcion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("resultado");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Status", "ReceivedAt");

                    b.ToTable("Denuncia", (string)null);
                });

            modelBuilder.Entity("EBR.Domain.Workflow.HealthAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("numero_alerta");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_decision");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("motivo_decision");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("producto");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_recepcion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("resultado");

                    b.HasKey("Id");

                    b.HasIndex("AlertNumber")
                        .IsUnique();

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Status", "ReceivedAt");

                    b.ToTable("Alerta_LAPCH", (string)null);
                });

            modelBuilder.Entity("EBR.Domain.Workflow.InspectionCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prioridad");

                    b.Property<int>("SourceReferenceId")
                        .HasColumnType("integer")
                        .HasColumnName("origen_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_origen");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SourceType", "SourceReferenceId")
                        .IsUnique();

                    b.HasIndex("Status", "Priority", "CreatedAt");

                    b.ToTable("Caso", (string)null);
                });

            modelBuilder.Entity("EBR.Domain.Workflow.InstitutionalScheduling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observaciones");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("motivo");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CompanyId", "CreatedAt");

                    b.ToTable("Programacion_Institucional", (string)null);
                });

            modelBuilder.Entity("EBR.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("RequestedRole")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EBR.Infrastructure.Identity.PasswordRecoveryCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("PasswordRecoveryCode", (string)null);
                });

            modelBuilder.Entity("EBR.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("EBR.Infrastructure.Identity.UserRegistrationDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_documento");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("hash");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tipo_mime");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("StorageReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("referencia_almacenamiento");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_carga");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DocumentType");

                    b.ToTable("Documento_Registro_Usuario", null, t =>
                        {
                            t.HasCheckConstraint("CK_Documento_Registro_Tipo", "tipo_documento IN ('CARTA_AUTORIZACION')");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EBR.Domain.Companies.CompanyHistoryEntry", b =>
                {
                    b.HasOne("EBR.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBR.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Domain.Companies.CompanyRepresentative", b =>
                {
                    b.HasOne("EBR.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Domain.Companies.CompanyUser", b =>
                {
                    b.HasOne("EBR.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBR.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Domain.Evaluations.EvaluationGuidanceCriterion", b =>
                {
                    b.HasOne("EBR.Domain.Evaluations.EvaluationTemplateItem", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Domain.Evaluations.EvaluationImportBatch", b =>
                {
                    b.HasOne("EBR.Domain.Evaluations.EvaluationTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EBR.Domain.Evaluations.EvaluationImportRow", b =>
                {
                    b.HasOne("EBR.Domain.Evaluations.EvaluationImportBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Domain.Evaluations.EvaluationQualificationRule", b =>
                {
                    b.HasOne("EBR.Domain.Evaluations.EvaluationTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Domain.Evaluations.EvaluationResponseOption", b =>
                {
                    b.HasOne("EBR.Domain.Evaluations.EvaluationTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Domain.Evaluations.EvaluationTemplateItem", b =>
                {
                    b.HasOne("EBR.Domain.Evaluations.EvaluationTemplateItem", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EBR.Domain.Evaluations.EvaluationTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.CompanyFoodSubcategory", b =>
                {
                    b.HasOne("EBR.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBR.Domain.RiskCatalogs.FoodSubcategory", null)
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.CompanyRiskFactorValue", b =>
                {
                    b.HasOne("EBR.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBR.Domain.RiskCatalogs.StructuralRiskFactor", null)
                        .WithMany()
                        .HasForeignKey("FactorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBR.Domain.RiskCatalogs.StructuralRiskOption", null)
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBR.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RegisteredBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.FoodSubcategory", b =>
                {
                    b.HasOne("EBR.Domain.RiskCatalogs.FoodCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBR.Domain.RiskCatalogs.RiskLevel", null)
                        .WithMany()
                        .HasForeignKey("ChemicalRiskLevelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EBR.Domain.RiskCatalogs.RiskLevel", null)
                        .WithMany()
                        .HasForeignKey("MicrobiologicalRiskLevelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EBR.Domain.RiskCatalogs.RiskLevel", null)
                        .WithMany()
                        .HasForeignKey("TotalRiskLevelId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.FoodSubcategoryHazard", b =>
                {
                    b.HasOne("EBR.Domain.RiskCatalogs.RiskScaleLevel", null)
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBR.Domain.RiskCatalogs.FoodSubcategory", null)
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.InspectionFrequencyMatrix", b =>
                {
                    b.HasOne("EBR.Domain.RiskCatalogs.RiskLevel", null)
                        .WithMany()
                        .HasForeignKey("RiskLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBR.Domain.RiskCatalogs.RiskRuleVersion", null)
                        .WithMany()
                        .HasForeignKey("RuleVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EBR.Domain.RiskCatalogs.RiskScaleLevel", null)
                        .WithMany()
                        .HasForeignKey("ScaleLevelId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.RiskCalculation", b =>
                {
                    b.HasOne("EBR.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBR.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("GeneratedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBR.Domain.RiskCatalogs.InspectionFrequencyMatrix", null)
                        .WithMany()
                        .HasForeignKey("InspectionFrequencyMatrixId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBR.Domain.RiskCatalogs.RiskLevel", null)
                        .WithMany()
                        .HasForeignKey("RiskLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBR.Domain.RiskCatalogs.RiskRuleVersion", null)
                        .WithMany()
                        .HasForeignKey("RuleVersionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.RiskRuleVersion", b =>
                {
                    b.HasOne("EBR.Domain.RiskCatalogs.RiskScale", null)
                        .WithMany()
                        .HasForeignKey("FrequencyScaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBR.Domain.RiskCatalogs.RiskScale", null)
                        .WithMany()
                        .HasForeignKey("ProductScaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.RiskScaleLevel", b =>
                {
                    b.HasOne("EBR.Domain.RiskCatalogs.RiskScale", null)
                        .WithMany("Levels")
                        .HasForeignKey("ScaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.StructuralRiskFactor", b =>
                {
                    b.HasOne("EBR.Domain.RiskCatalogs.RiskRuleVersion", null)
                        .WithMany()
                        .HasForeignKey("RuleVersionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.StructuralRiskOption", b =>
                {
                    b.HasOne("EBR.Domain.RiskCatalogs.StructuralRiskFactor", null)
                        .WithMany("Options")
                        .HasForeignKey("FactorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Domain.Workflow.BpmRequest", b =>
                {
                    b.HasOne("EBR.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBR.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Domain.Workflow.BpmRequestDocument", b =>
                {
                    b.HasOne("EBR.Domain.Workflow.BpmRequest", null)
                        .WithMany()
                        .HasForeignKey("BpmRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Domain.Workflow.CaseAssignment", b =>
                {
                    b.HasOne("EBR.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBR.Domain.Workflow.InspectionCase", null)
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBR.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Domain.Workflow.CaseStateHistory", b =>
                {
                    b.HasOne("EBR.Domain.Workflow.InspectionCase", null)
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBR.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Domain.Workflow.Complaint", b =>
                {
                    b.HasOne("EBR.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EBR.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Domain.Workflow.HealthAlert", b =>
                {
                    b.HasOne("EBR.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBR.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Domain.Workflow.InspectionCase", b =>
                {
                    b.HasOne("EBR.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBR.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Domain.Workflow.InstitutionalScheduling", b =>
                {
                    b.HasOne("EBR.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBR.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Infrastructure.Identity.UserRegistrationDocument", b =>
                {
                    b.HasOne("EBR.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("EBR.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("EBR.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EBR.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("EBR.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.RiskScale", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("EBR.Domain.RiskCatalogs.StructuralRiskFactor", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
