namespace EBR.Infrastructure.Evaluations;

/// <summary>Nodo del árbol de la ficha, con la celda de la que se copió su texto.</summary>
public sealed record BpmTemplateNode(string Code, string? ParentCode, string ItemType, string Description, string SourceCell);

/// <summary>Criterio de la guía de llenado con su marca de criticidad tal como aparece en la hoja.</summary>
public sealed record BpmGuidanceEntry(string ItemCode, string Code, string Description, string? CriticalityMark, string SourceCell);

/// <summary>Banda de calificación de la ficha.</summary>
public sealed record BpmQualificationBand(
    string Code,
    string Description,
    string Classification,
    string Action,
    decimal? MinPercentage,
    bool MinIncluded,
    decimal? MaxPercentage,
    bool MaxIncluded,
    string SourceCell);

/// <summary>
/// Contenido normativo de la Ficha de Inspección BPM (código FO-DDA-XX, versión 1.00, mayo de 2024)
/// y de su guía de llenado (IT-DDA-XX). Los textos se copian literalmente de las celdas indicadas;
/// solo se recortan los espacios iniciales y finales. Los archivos fuente no se versionan.
/// </summary>
public static class BpmTemplateData
{
    public const string TemplateName = "Ficha de Inspección BPM";
    public const string FormSheet = "Ficha Inspección BPM";
    public const string GuideSheet = "Guía de Llenado";

    public const string Chapter = "CHAPTER";
    public const string Section = "SECTION";
    public const string Subsection = "SUBSECTION";
    public const string Group = "GROUP";
    public const string Question = "QUESTION";

    public static readonly IReadOnlyList<BpmTemplateNode> Nodes =
    [
        new("1", null, Chapter, "1. ESTABLECIMIENTO - DISEÑO DE LAS INSTALACIONES Y EQUIPO", "A37"),
        new("1.1", "1", Section, "1.1. Ubicación y estructura", "A38"),
        new("1.1.1", "1.1", Subsection, "1.1.1. Ubicación del establecimiento", "A39"),
        new("1.1.1.a", "1.1.1", Question, "a) Ubicación adecuada", "B40"),
        new("1.1.1.b", "1.1.1", Question, "b) Alrededores limpios", "B41"),
        new("1.1.1.c", "1.1.1", Question, "c) Ausencia de focos de contaminación", "B42"),
        new("1.1.2", "1.1", Subsection, "1.1.2. Diseño y disposición del establecimiento", "A45"),
        new("1.1.2.a", "1.1.2", Question,
            "a) El diseño y la disposición del establecimiento permite la limpieza y el mantenimiento de manera adecuada.", "B46"),
        new("1.1.2.b", "1.1.2", Question,
            "b) La disposición de las áreas y el flujo de las operaciones evitan o reducen al mínimo la contaminación cruzada.", "B47"),
        new("1.1.3", "1.1", Subsection, "1.1.3. Estructuras internas y accesorios", "A50"),
        new("1.1.3.1", "1.1.3", Group, "1.1.3.1. Paredes", "B51"),
        new("1.1.3.1.a", "1.1.3.1", Question,
            "Las paredes deben tener una superficie lisa adecuada a las actividades que se realicen, construídas con materiales impermeables de fácil limpieza y, cuando sea necesario, de fácil desinfección.", "C52"),
        new("1.1.3.2", "1.1.3", Group, "1.1.3.2. Pisos", "B55"),
        new("1.1.3.2.a", "1.1.3.2", Question,
            "Construidos con materiales impermeables de fácil limpieza sin grietas, uniones redondeadas con las paredes y que faciliten el drenaje.", "C56"),
        new("1.1.3.3", "1.1.3", Group, "1.1.3.3. Techos", "B59"),
        new("1.1.3.3.a", "1.1.3.3", Question,
            "Construidos de manera que reduzcan al mínimo la acumulación de suciedad y de condensación, así como el desprendimiento de partículas.", "C60"),
        new("1.1.3.4", "1.1.3", Group, "1.1.3.4. Ventanas", "B63"),
        new("1.1.3.4.a", "1.1.3.4", Question,
            "a) Fáciles de limpiar y construídas de modo que se reduzca al mínimo la acumulación de suciedad.", "C64"),
        new("1.1.3.4.b", "1.1.3.4", Question,
            "b) Provistas de malla contra insectos fácil de desmontar y limpiar.", "C65"),
        new("1.1.3.5", "1.1.3", Group, "1.1.3.5. Puertas", "B68"),
        new("1.1.3.5.a", "1.1.3.5", Question,
            "Tienen una superficie lisa y no absorbente, son fáciles de limpiar y, cuando sea necesario, de desinfectar.", "C69"),
        new("1.1.3.6", "1.1.3", Group, "1.1.3.6.  Superficies en contacto con los alimentos", "B72"),
        new("1.1.3.6.a", "1.1.3.6", Question,
            "Deben estar construídos con materiales inertes, en buenas condiciones, ser duraderas y fáciles de limpiar, mantener y desinfectar.", "C73"),
        new("1.2", "1", Section, "1.2. Instalaciones", "A76"),
        new("1.2.1", "1.2", Subsection, "1.2.1. Drenaje y eliminación de residuos", "A77"),
        new("1.2.1.a", "1.2.1", Question,
            "a) El sistema de drenaje está diseñado y construído de manera que se evite la contaminación de los alimentos o del suministro de agua potable.", "B78"),
        new("1.2.1.b", "1.2.1", Question,
            "b) Los residuos sólidos son recogidos y eliminados por personal calificado y deben ser depositados en contenedores debidamente identificados, construidos con material impermeable, ubicados en áreas que eviten la infestación por plagas y cuando corresponda, se podrán cerrar con llave para evitar la contaminación accidental o intencionada de los alimentos.", "B79"),
        new("1.2.2", "1.2", Subsection, "1.2.2. Instalaciones de limpieza", "A82"),
        new("1.2.2.a", "1.2.2", Question,
            "La planta cuenta con estaciones separadas para el lavado y desinfección de alimentos, equipos, utensilios y manos, al igual que para el lavado de los equipos utilizados en la limpieza de los servicios sanitarios, los drenajes y contenedores, todas dotadas con suficiente agua potable.", "B83"),
        new("1.2.3", "1.2", Subsection, "1.2.3. Instalaciones para la higiene personal y servicios sanitarios", "A86"),
        new("1.2.3.a", "1.2.3", Question,
            "a) Los establecimientos cuentan con un filtro sanitario a la entrada del área de producción.", "B87"),
        new("1.2.3.b", "1.2.3", Question,
            "b) Servicios sanitarios separados por sexo, con suficientes lavamanos, inodoros, urinales y duchas.", "B88"),
        new("1.2.3.c", "1.2.3", Question,
            "c) Cuando sea necesario, vestidores con casilleros y espejos debidamente ubicados.", "B89"),
        new("1.2.4", "1.2", Subsection, "1.2.4. Temperatura", "A92"),
        new("1.2.4.a", "1.2.4", Question,
            "a) El establecimiento cuenta con instalaciones adecuadas para el calentamiento, enfriamiento, cocción, refrigeración o congelamiento y para el almacenamiento de alimentos refrigerados o congelados dependiendo de las operaciones que realiza,", "B93"),
        new("1.2.4.b", "1.2.4", Question,
            "b) El establecimiento cuenta con la capacidad para controlar la temperatura ambiente de acuerdo a la naturaleza del prouducto, con el objeto de garantizar la inocuidad y la idoneidad de los alimentos.", "B94"),
        new("1.2.5", "1.2", Subsection, "1.2.5. Calidad del aire y ventilación", "A97"),
        new("1.2.5.a", "1.2.5", Question,
            "El establecimiento cuenta con medios adecuados de ventilación natural o mecánica, diseñados y construídos de manera que el aire no circule de zonas contaminadas a zonas limpias y que se facilite su mantenimiento y limpieza.", "B98"),
        new("1.2.6", "1.2", Subsection, "1.2.6. Iluminación", "A101"),
        new("1.2.6.a", "1.2.6", Question,
            "a) Se dispone de iluminación natural o artificial adecuada que permita a la empresa realizar las actividades alimentarias de manera higiénica.", "B102"),
        new("1.2.6.b", "1.2.6", Question,
            "b) La intensidad debe ser suficiente para la naturaleza de la actividad que se realice.", "B103"),
        new("1.2.6.c", "1.2.6", Question,
            "c) Las luminarias  están protegidas, cuando corresponda, para garantizar que los alimentos no se contaminen en caso de rotura de los elementos de iluminación.", "B104"),
        new("1.2.7", "1.2", Subsection, "1.2.7. Almacenamiento", "A107"),
        new("1.2.7.a", "1.2.7", Question,
            "El establecimieno cuenta con instalaciones separadas y adecuadas para el almacenamiento de los productos terminados, materias primas, material de empaque, productos de limpieza, lubricantes y combustibles.", "B108"),
        new("1.3", "1", Section, "1.3. Equipo", "A111"),
        new("1.3.a", "1.3", Question,
            "El equipo y los recipientes que estan en contacto con los alimentos deben ser aptos para el contacto con los alimentos, estar diseñados, fabricados y ubicados de manera que se puedan limpiar, desinfectar y mantener adecuadamente para evitar la contaminación de los alimentos.", "B112"),

        new("2", null, Chapter, "2. CAPACITACIÓN Y COMPETENCIA", "A115"),
        new("2.1", "2", Section, "2.1. Conocimiento y responsabilidades", "A116"),
        new("2.1.a", "2.1", Question,
            "El personal debe tener conocimiento de su función y responsabilidad en cuanto a la protección de los alimentos contra la contaminación o el deterioro.", "B117"),
        new("2.2", "2", Section, "2.2. Programas de capacitación", "A120"),
        new("2.2.a", "2.2", Question,
            "El establecimiento cuenta con un programa escrito de capacitación, principalmente en higiene y manipulación de alimentos, BPM e higiene personal.", "B121"),
        new("2.3", "2", Section, "2.3. Instrucción y supervisión", "A124"),
        new("2.3.a", "2.3", Question,
            "Los encargados, supervisores y los operarios cuentan con los conocimientos suficientes sobre los principios y prácticas de higiene de los alimentos para poder identificar las desviaciones y adoptar las medidas necesarias que correspondan a su puesto.", "B125"),

        new("3", null, Chapter,
            "3. MANTENIMIENTO, LIMPIEZA, DESINFECCIÓN Y CONTROL DE PLAGAS EN EL ESTABLECIMIENTO", "A128"),
        new("3.1", "3", Section, "3.1. Mantenimiento y limpieza", "A129"),
        new("3.1.1", "3.1", Subsection, "3.1.1. Consideraciones generales", "A130"),
        new("3.1.1.a", "3.1.1", Question,
            "Se  utilizan equipos y utensilios de limpieza adecuadamente diseñados para las diferentes áreas, se conservan limpios, reciben mantenimiento y se sustituyen periódicamente a fin de que no se conviertan en una fuente de contaminación para las superficies o los alimentos.", "B131"),
        new("3.1.2", "3.1", Subsection, "3.1.2. Métodos y procedimientos de limpieza y desinfección", "A134"),
        new("3.1.2.a", "3.1.2", Question,
            "Los procedimientos de limpieza y desinfección garantizan que todas las partes del establecimiento están adecuadamente limpias y cuando corresponda desinfectadas.", "B135"),
        new("3.1.3", "3.1", Subsection, "3.1.3 Monitoreo/seguimiento de la eficacia", "A138"),
        new("3.1.3.a", "3.1.3", Question,
            "Se realiza el seguimiento de la eficacia de la aplicación de los procedimientos de limpieza y desinfección y se verifica que se han aplicado adecuadamente.", "B139"),
        new("3.2", "3", Section, "3.2. Sistemas de control de plagas", "A142"),
        new("3.2.a", "3.2", Question,
            "El establecimiento cuenta con un Programa escrito para el control de plagas y con las barreras físicas necesarias para impedir que penetren a la planta.", "B143"),

        new("4", null, Chapter, "4. HIGIENE PERSONAL", "A146"),
        new("4.a", "4", Question,
            "La empresa tiene establecidas políticas y procedimientos adecuados  en materia de higiene personal.", "B147"),

        new("5", null, Chapter, "5. . CONTROL DE LAS OPERACIONES", "A150"),
        new("5.1", "5", Section, "5.1. Descripción de los productos y procesos", "A151"),
        new("5.1.1", "5.1", Subsection, "5.1.1. Descripción del producto", "A152"),
        new("5.1.1.a", "5.1.1", Question,
            "El establecimiento describe sus productos de manera individual o por grupo de alimentos de manera adecuada.", "B153"),
        new("5.1.2", "5.1", Subsection, "5.1.2. Descripción fases del proceso", "A156"),
        new("5.1.2.a", "5.1.2", Question,
            "El establecimiento tiene elaborado los diagramas  de flujo de los productos y líneas de productos actualizados.", "B157"),
        new("5.1.3", "5.1", Subsection, "5.1.3. Monitoreo/seguimiento, medidas correctivas y verificación", "A160"),
        new("5.1.3.a", "5.1.3", Question,
            "El establecimiento cuenta con procedimintos escritos sobre el monitoreo de las prácticas de higiene y realiza actividades de verificación de su efectividad.", "B161"),
        new("5.2", "5", Section, "5.2. Aspectos fundamentales de las BPM", "A164"),
        new("5.2.1", "5.2", Subsection,
            "5.2.1. Especificaciones microbiológicas, físicas, químicas y de alérgenos", "A165"),
        new("5.2.1.a", "5.2.1", Question,
            "Las especificaciones microbiológicas, físicas, químicas y de alérgenos del producto están definidas en base a las normas oficiales y contribuyen a la inocuidad del producto.", "B166"),
        new("5.2.2", "5.2", Subsection, "5.2.2. Materiales y materias primas", "A169"),
        new("5.2.2.a", "5.2.2", Question,
            "El establecimiento mantiene un sistema de control para asegurar que las materias primas y otros ingredientes a ser utilizados en la elaboración de alimentos son conformes con las especificaciones de calidad e inocuidad establecidas en las espcificaciones.", "B170"),
        new("5.2.3", "5.2", Subsection, "5.2.3. Envasado", "A173"),
        new("5.2.3.a", "5.2.3", Question,
            "El diseño y los materiales utilizados para envasar los alimentos son inocuos y adecuados para proteger el producto contra la contaminación.", "B174"),
        new("5.3", "5", Section, "5.3. Agua", "A177"),
        new("5.3.a", "5.3", Question,
            "El establecimiento cuenta con suficiente abastecimiento de agua potable y con instalaciones apropiadas para su almacenamiento y distribución.", "B178"),
        new("5.4", "5", Section, "5.4. Procedimientos de retiro del mercado", "A181"),
        new("5.4.a", "5.4", Question,
            "a) El establecimiento cuenta con los procedimientos adecuados de retiro de alimentos del mercado.", "B182"),
        new("5.4.b", "5.4", Question,
            "b) Los productos devueltos o retirados del mercado  se mantienen en condiciones seguras de almacenamiento según lo estipulado en los procedimeintos.", "B183"),

        new("6", null, Chapter, "6. INFORMACIÓN SOBRE LOS PRODUCTOS Y SENSIBILIZACIÓN DEL CONSUMIDOR", "A186"),
        new("6.1", "6", Section, "6.1. Etiquetado de los productos", "A187"),
        new("6.1.a", "6.1", Question,
            "Los productos eleborados cumplen a cabalidad con la NORDOM 53, Etiquetado general de los productos previamente envasados (pre-envasados)", "B188"),

        new("7", null, Chapter, "7. TRANSPORTE", "A191"),
        new("7.a", "7", Question,
            "Los medios de transporte son adecuados a la  naturaleza de los productos que  transportan y permiten, cuando procede, el control de temperatura, el grado de humedad, el aire y otras condiciones necesarias para proteger los alimentos contra la proliferación de microorganismos nocicos y el deterioro.", "B192")
    ];

    public static readonly IReadOnlyList<BpmQualificationBand> QualificationBands =
    [
        new("CAL-1", "≤ 60%", "Condiciones inaceptables", "Considerar cierre", null, false, 60m, true, "D198"),
        new("CAL-2", "> 60% - 70%", "Condiciones deficientes", "Urge corregir", 60m, false, 70m, true, "D199"),
        new("CAL-3", "> 70% - 80%", "Condiciones regulares", "Necesario hacer correcciones", 70m, false, 80m, true, "D200"),
        new("CAL-4", "> 80%", "Buenas condiciones", "Hacer agunas correcciones", 80m, false, null, false, "D201")
    ];

    public static readonly IReadOnlyList<BpmGuidanceEntry> Guidance =
    [
        new("1.1.1.a", "i", "i. El establecimiento no debe estar ubicado en zonas ambientalmente contaminadas y de actividades industriales que tengan una probabilidad razonable de contaminar los alimentos.", null, "C52"),
        new("1.1.1.a", "ii", "ii. El establecimiento no está ubicado en zonas expuestas a inundaciones.", null, "C55"),
        new("1.1.1.a", "iii", "iii. El establecimiento no está ubicado en zonas expuestas a infestaciones de plagas.", null, "C56"),
        new("1.1.1.a", "iv", "iv. El esablecinmiento no debe estar ubicado en zonas de las que no puedan retirarse de manera eficaz los residuos sólidos y líquidos.", null, "C58"),
        new("1.1.1.b", "i", "i. Las áreas circundantes deben estar libres de malezas, basuras y desperdicios.", null, "C61"),
        new("1.1.1.b", "ii", "ii. Los equipos en desuso ubicados en el pátio deben estar identificados y almacenados adecuadamente.", null, "C63"),
        new("1.1.1.c", "i", "i. Sistema adecuado de tratamiento de desperdicios sólidos y líquidos.", null, "C66"),
        new("1.1.1.c", "ii", "ii.Inexistencia de lugares que se puedan constituir en atracción o refugio para insectos y roedores.", null, "C67"),
        new("1.1.2.a", "i", "i. Diseño de la planta en función del producto a elaborar.", null, "C71"),
        new("1.1.2.a", "ii", "ii. El flujo de las operaciones permite que el movimiento del personal y los materiales minimice la porisibilidad de la contaminación cruzada", null, "C72"),
        new("1.1.2.b", "i", "i. Las áreas de almacenamiento de materiales, materias primas y productos terminados están físicamente separadas", null, "C75"),
        new("1.1.2.b", "ii", "ii. Tamaño adecuado que permita las labores de producción, mantenimiento, limpieza y desinfección.", null, "C77"),
        new("1.1.3.1.a", "i", "i. Las paredes son lisas hasta una altura adedcuada a las actividades que se realizan.", null, "D81"),
        new("1.1.3.1.a", "ii", "ii. Son de materiales impermeables, se mantienen limpias, pintadas con colores claros y libres de desprendimeintos de pintura.", null, "D83"),
        new("1.1.3.1.a", "iii", "iii. Están libres de grietas y orificios.", null, "D85"),
        new("1.1.3.2.a", "i", "i. Construidos con materiales impermeables resistentes a los ácidos y álcalis y de fácil limpieza", null, "D87"),
        new("1.1.3.2.a", "ii", "ii. Deben ser lisos, sin grietas y con uniones redondeadas con las paredes.", null, "D88"),
        new("1.1.3.2.a", "iii", "iii. Con pendiete adecuada para facilitar el drenaje.", null, "D90"),
        new("1.1.3.3.a", "i", "i. Deben estar construidos y acabados de forma que reduzcan al mínimo la acumulación de suciedad y de condensación.", null, "D92"),
        new("1.1.3.3.a", "ii", "ii. Pintura en buen estado sin desprendimiento de partículas.  y fáciles de limpiar.", null, "D94"),
        new("1.1.3.3.a", "iii", "iii. Ausencia de elementos colgantes sobre el área de producción", null, "D96"),
        new("1.1.3.4.a", "i", "i. Las ventanas son fáciles de limpiar", null, "D100"),
        new("1.1.3.4.a", "ii", "ii. Ausencia de suciedad acumulada", null, "D101"),
        new("1.1.3.4.a", "iii", "iii. Las ventasnas y sus marcos no presentan señales de deterioro", null, "D102"),
        new("1.1.3.4.b", "i", "i. Las ventanas estar provistas de malla contra insectos", null, "D104"),
        new("1.1.3.4.b", "ii", "ii. Las mallas contra insectos son fáciles de desmontar y limpiar", null, "D105"),
        new("1.1.3.4.b", "iii", "iii. Las mallas protectoras  no presentan señales de deterioro", null, "D106"),
        new("1.1.3.5.a", "i", "i. Tienen una superficie lisa no absorbente y son fáciles de limpiar", null, "D108"),
        new("1.1.3.5.a", "ii", "ii. Las puertas deben estar ajustadas a sus marcos y no prsentar signos de deterioro", null, "D109"),
        new("1.1.3.5.a", "iii", "ii. Preferiblemente deben abrir hacia afuera.", null, "D112"),
        new("1.1.3.6.a", "i", "i. Están hechas de materiales lisos, no absorbentes e inertes a los alimentos, detergentes y desinfectantes.", null, "D114"),
        new("1.1.3.6.a", "ii", "ii. Están en buenas condiciones, son duraderas y fáciles de limpiar, mantener y desinfectar.", null, "D116"),
        new("1.2.1.a", "i", "i. Está diseñados para manejar el volumen de agua requerido por las operaciones de la emprsa", null, "D122"),
        new("1.2.1.a", "ii", "ii. Tienen sifones que evitan el reflujo y el retorno de malos olores.", null, "D124"),
        new("1.2.1.a", "iii", "iii. El drenaje no fluye de zonas muy  contaminadas  a zonas en las que los alimentos terminados estén expuestos al ambiente.", null, "D125"),
        new("1.2.1.b", "i", "i. Los residuos son recogidos y eliminados por personal capacitado y, cuando corresponda mantienen registros de su eliminación.", null, "D128"),
        new("1.2.1.b", "ii", "ii. Los contenedores están debidamente identificados y ubicados lejos del área de producción para evitar la infestación con plagas.", null, "D130"),
        new("1.2.1.b", "iii", "iii. Los contenedores están construidos con materiales impermeables y en caso de almacenar materiales perligrosos deben estar cerrados con llave.", null, "D132"),
        new("1.2.2.a", "i", "i. Las instalaciones disponen de un suministro suficiente de agua potable y cuando corresponda, de agua caliente.", null, "C136"),
        new("1.2.2.a", "ii", "ii. Se dispone de estaciones separadas para el lavado y  desinfección de los alimentos, los equipos y utensilios y el lavado de manos.", null, "C138"),
        new("1.2.2.a", "iii", "iii. Disponen de estaciones separadas para la limpieza de los equipos utilizados en la limpieza de los servicios sanitarios, los drenajes y contenedores de residuos sólidos.", null, "C140"),
        new("1.2.3.a", "i", "i. El filtro sanitario está equipado acorde con las operaciones de la planta.", null, "D145"),
        new("1.2.3.a", "ii", "ii. Todos los equipos se mantienenen perfecto estado de funcionamiento.", null, "D147"),
        new("1.2.3.a", "iii", "iii. Está equipado con jabón líquido, desinfectante y toallas desechables.", null, "D149"),
        new("1.2.3.a", "iv", "iv. Tienen rótulos indicando la secuencia de pasos para utilizar el filtro sanitario y la forma correcta de lavarse las manos.", null, "D151"),
        new("1.2.3.b", "i", "i, Los servvicios sanitarios es encuentran limpios, en buen estado y habilitados con papel higiénico y zafacones con tapa.", null, "D154"),
        new("1.2.3.b", "ii", "ii. Lavamanos con abastecimiento de agua accionados por pedales, rodillas, sensores, etc., con jabón líquido desinfectante, toallas de papel o secadores de aire y rótulos que indican como lavarse las manos adecuadamente.", null, "D156"),
        new("1.2.3.b", "iii", "iii. Las puertas no abren directamente hacia el área de proceso.", null, "D160"),
        new("1.2.3.c", "i", "i. Los vestidores se mantienen limpios.", null, "D162"),
        new("1.2.3.c", "ii", "ii. Los casilleros se mantienen en buen estado.", null, "D163"),
        new("1.2.3.c", "iii", "iii. Los espejos y asientos se mantien en buen estado", null, "D164"),
        new("1.2.4.a", "i", "i. El equipo utilizado para cocer, calentar, enfriar, refrigerar, congelar o almacenar alimentos está diseñado de modo que el alimento alcance la temperatura requerida con la mayor rapidez posible y la mantene de manera eficaz.", "C", "D170"),
        new("1.2.4.a", "ii", "ii.  El establecimiento cuenta con un sistema adecuado para controlar el tiempo y la temperatura durante la cocción, el enfriamiento, la refrigeración, la congelación y el almacenamiento.", "C", "D174"),
        new("1.2.4.a", "iii", "iii. En el sistema se especifica con claridad los límites tolerables para las variaciones de tiempo y temperatura.", "C", "D177"),
        new("1.2.4.a", "iv", "iv. Los equipos utilizados para monitorear y controlar el tiempo y la temperatura son sometidos a procesos de mantenimiento y calibración de acuerdo a lo especificado por el fabricante.", "M", "D179"),
        new("1.2.4.a", "v", "v. El establecimiento mantiene los registros escritos del monitoreo y control del tiempo y temperatura y del mantenimiento y calibración de los equipos.", "M", "D182"),
        new("1.2.4.b", "i", "i. En el sistema se especifica con claridad los límites tolerables para las variaciones de tiempo y temperatura.", null, "D188"),
        new("1.2.4.b", "ii", "ii, Cuenta con medios para monitorear, controlar y dar seguimiento a la temperatura y humedad.", null, "D190"),
        new("1.2.5.a", "i", "i. El sistema de ventilación reduce al mínimo la contaminación de los alimentos transmitida por el aire.", null, "C193"),
        new("1.2.5.a", "ii", "ii. El sistema de ventilación contribuye con el control de la temperatura ambiente.", null, "C195"),
        new("1.2.5.a", "iii", "iii. El sistema de ventilación contribuye con el contro de los olores y la humedad para garantizar la inocuidad y la idoneidad de los alimentos.", null, "C197"),
        new("1.2.6", "i", "i. La iluminación debe ser suficiente para detectar defectos o contaminantes en los alimentos, o de examinar las instalaciones y el equipo para comprobar su limpieza.", null, "C200"),
        new("1.2.6", "ii", "ii. La intensidad debe ser suficiente para la naturaleza de la actividad que se realice.", null, "C203"),
        new("1.2.6", "iii", "iii, Cuando corresponda, las luminarias  están protegidas, , para garantizar que los alimentos no se contaminen en caso de rotura de los elementos de iluminación.", null, "C205"),
        new("1.2.7.a", "i", "i. Las instalaciones de almacenamiento faciliten un mantenimiento y una limpieza adecuados.", "m", "C209"),
        new("1.2.7.a", "ii", "ii. Las instalaciones de almacenamiento eviten el acceso y el anidamiento de plagas.", "C", "C211"),
        new("1.2.7.a", "iii", "iii. Las instalaciones de almacenamiento permiten que los alimentos estén protegidos eficazmente de la contaminación, incluido el contacto cruzado con alérgenos.", "M", "C213"),
        new("1.2.7.a", "iv", "iv.  Las instalaciones de almacenamiento cuentan con medios para el control de la temperatura y humedad, cuando aplique.", "C", "C216"),
        new("1.3.a", "i", "i. El equipo y los recipientes están fabricados con materiales que no sean potencialmente tóxicos para el uso al que se destinan.", "C", "B219"),
        new("1.3.a", "ii", "ii. Están diseñados, fabricados y ubicados de manera que se puedan limpiar y desinfectar adecuadamente.", "C", "B221"),
        new("1.3.a", "iii", "iii. Están instalados de manera que se facilite su mantenimiento.", "m", "B223"),
        new("2.1.a", "i", "i. El personal cuenta con los conocimientos y capacidades necesarios para poder manipular los alimentos en condiciones higiénicas.", null, "B227"),
        new("2.1.a", "ii", "ii. El personal que manipula alimentos  ha sido capacitado en el uso adecuado  productos químicos de limpieza u otras sustancias químicas potencialmente peligrosas para evitar la contaminación de los alimentos.", null, "B229"),
        new("2.2.a", "i", "i. El programa contempla la naturaleza de los peligros asociados con los alimentos, por ejemplo, su capacidad para favorecer la proliferación de microorganismos patógenos o que causen deterioro, la existencia de posibles contaminantes físicos o alérgenos conocidos.", null, "B233"),
        new("2.2.a", "ii", "ii. La manera en que se elaboran, manipulan, envasan y almacenan los alimentos, incluida la probabilidad de contaminación.", null, "B237"),
        new("2.2.a", "iii", "iii. El tiempo que se prevé que transcurra antes del consumo del alimento.", null, "B239"),
        new("2.2.a", "iv", "iv. El uso y el mantenimiento de los utensilios y el equipo relacionados con los alimentos.", null, "B240"),
        new("2.2.a", "v", "v. El programa de capacitación se revisa rutinariamente y se actualiza cuando sea necesario.", null, "B242"),
        new("2.3.a", "i", "i.Se realizan evaluaciones periódicas de la eficacia de los programas de capacitación e instrucción.", "m", "B245"),
        new("2.3.a", "ii", "ii. Se garantiza que los procedimientos se  realizan de forma adecuada por medio de supervisiones y verificaciones rutinarias.", "M", "B247"),
        new("2.3.a", "iii", "iii.  El personal encargado del control de los alimentos está capacitado adecuadamente para las runciones que realiza", "C", "B249"),
        new("3.1.1.a", "i", "i. En las zonas de preparación y almacenamiento de alimentos se utilizan productos de limpieza especializados para superficies que entran en contacto con los alimentos.", "m", "C255"),
        new("3.1.1.a", "ii", "ii. Los productos químicos para la limpieza y desinfección se  manejan y utilizan según las instrucciones de los fabricantes", "M", "C258"),
        new("3.1.1.a", "iii", "iii. El equipo de limpieza se almacena en un lugar adecuado y de modo tal que se evite la contaminación.", "M", "C260"),
        new("3.1.2.a", "i", "i. El establecimiento cuenta con procedimientos escritos de limpieza y desinfección (POES)", "C", "C263"),
        new("3.1.2.a", "ii", "ii. Los procedimientos de limpieza no provocan la contaminación de los alimentos,", null, "C265"),
        new("3.1.2.a", "iii", "iii. La concentración y el tiempo de aplicación de los productos químicos utilizados para la desinfección se emplean según las instrucciones del fabricante.", null, "C267"),
        new("3.1.3.a", "i", "i. Se toman medidas para tomar muestras y hacer pruebas del medio ambiente y de las superficies que entran en contacto con los alimentos.", "M", "C271"),
        new("3.1.3.a", "ii", "ii. En los casos que no proceda tomar muestras para realizar análisis microbiológicos, se monitorean los procedimientos de limpieza y desinfección, incluida la concentración correcta de desinfectante para asegurarse que se siguen los protocolos de forma adecuada.", "M", "C273"),
        new("3.1.3.a", "iii", "iii. Los procedimientos de limpieza y desinfección y de mantenimiento se revisan periódicamente, se adaptan para reflejar cualquier cambio de circunstancias y se documentan como corresponda.", "M", "C277"),
        new("3.2.a", "i", "i. El establecimiento y las áreas circundantes se inspeccionan de forma regular para detectar indicios de infestación.", null, "B281"),
        new("3.2.a", "ii", "ii. El programa contempla medidas de erradicación en caso de alguna invasión de plaga.", "M", "B283"),
        new("3.2.a", "iii", "iii. Los productos químidos utilizados son autorizados y no suponen una amenaza para la inocuidad o la idoneidad de los alimentos.", "M", "B285"),
        new("4.a", "i", "i. Al personal que presente síntomas o que  se sabe o sospeche que padece o es portador de alguna enfermedad que probablemente se transmita por medio de los alimentos no se le permite ingresar a ninguna área de manipulación de alimentos.", "C", "B289"),
        new("4.a", "ii", "ii. El personal mantiene un alto nivel de aseo personal y, cuando corresponda, utiliza ropa protectora, cubre cabezas, cubre barba, mascarilla y calzado adecuado.", "C", "B293"),
        new("4.a", "iii", "iii. Se aplican medidas para evitar la contaminación cruzada por parte del personal, a través de un correcto lavado de manos y, cuando procedaa, mediante el uso de guantes,", "C", "B296"),
        new("4.a", "iv", "iv. El persobnal que manipula alimentos debe evitar conductas que puedan contaminar los alimentos tales como:, fumar, vapear, escupir, comer, beber, estornudar, tocer, tocarse la boca o la nariz, etc.", null, "B299"),
        new("4.a", "v", "v. El personal que manipula alimentos no debe portar joyas, relojes, prendedores, cadenas, etc., al igual que pestañas y uñas postizas.", null, "B302"),
        new("4.a", "vi", "vi. El personal que visita el área de producción al igual que el personal de mantenimiento, debe llevar ropa protectora y cumplir con todos los requisitos exigidos a los manipuladores de alimentos..", null, "B304"),
        new("5.1.1.a", "i", "i. Se especifica el uso previsto del alimento", "m", "C311"),
        new("5.1.1.a", "ii", "ii. Se especifica si los productos están destinados a grupos de consumidores vulnerables.", "M", "C312"),
        new("5.1.1.a", "iii", "iii. Se especifica la composición de los ingredientes, Aw, pH y método de conservación.", "m", "C314"),
        new("5.1.1.a", "iv", "iv. Se espesifica la presencia de alérgenos", "C", "C316"),
        new("5.1.1.a", "v", "v. Se especifica cualquier límite pertinente establecido para el alimento por la autoridad competente o, en ausencia de esta, por la gerencia del establecimiento.", "M", "C317"),
        new("5.1.1.a", "vi", "vi. Se describen las instrucciones para su uso ulterior", "m", "C320"),
        new("5.1.1.a", "vii", "vii, Se especifican las condiciones necesarias de almacenamiento", null, "C321"),
        new("5.1.1.a", "viii", "viii. Se especifican los materiales de envasado utilizados para los alimentos", "m", "C322"),
        new("5.1.2.a", "i", "i. Los diagramas de flujo contienen todas las fases de las actividades relativas a cada uno de los producto o línea de productos.", null, "C325"),
        new("5.1.2.a", "ii", "ii. Los diagramas de flujo muestran la secuencia y la interacción de todas las fases de la operación, incluidos los momentos en que las materias primas, ingredientes y productos intermedios se incorporan al flujo y cuándo se liberan y retiran los productos intermedios, subproductos y residuos.", null, "C327"),
        new("5.1.2.a", "iii", "iii. Los parámetros de control de las fases claves de producción de alimentos que contribuyen a la inocuidad tales como cocción, enfriado, congelado son monitoreados y sujetos a seguimiento.", "C", "C332"),
        new("5.1.3.a", "i", "i. Cuando se detectan no conformimades se toman las medidas correctivas de lugar.", "C", "C336"),
        new("5.1.3.a", "ii", "ii. El establecimiento realiza actividades de verificación de la efectividad y buena aplicación de los POE y los POES.", "M", "C338"),
        new("5.1.3.a", "iii", "iii. El establecimiento mantiene registros escritos sobre los hallazgos durante el monitoreo, sobre las medidas correctivas aplicadas y de las actividades de verificación durante un período superior a la vida útil del producto o durante el tiempo que establezca la autoridad competente.", "M", "C340"),
        new("5.2.1.a", "i", "i. Las especificaciones establecen los parámetros de muestreo, los métodos analíticos, los límites aceptables, y los procedimientos de monitoreo y seguimiento.", "m", "C347"),
        new("5.2.1.a", "ii", "ii.  Los alimentos crudos, que no se consideran listos para consumo, estan separados de los alimentos listos para el consumo.", "M", "C350"),
        new("5.2.1.a", "iii", "iii. Las áreas de elaboración donde existe un mayor riesgo de contaminación del alimento están debidamente indentificadas para restringir el acceso a las mismas", "M", "C352"),
        new("5.2.1.a", "iv", "iv. El establecimiento tiene implementado un sistema para impedir la contaminación fisica de los alimentos (tales como detectores de metales o detectores de rayos X).", "C", "C355"),
        new("5.2.1.a", "v", "v. Los productos de limpieza y desinfección al igual que los plaguicidas se  identifican, almacenan y se utilizan de forma segura a fin de evitar la contaminación de los alimentos, las superficies de contacto  y los materiales de envasado de alimentos.", "M", "C358"),
        new("5.2.1.a", "vi", "vi. Se llevan controles sobre los aditivos alimentarios y los coadyuvantes de elaboración cuyo uso inadecuado pudiera resultar perjudicial, a fin de que se utilicen únicamente de la manera prevista.", "M", "C362"),
        new("5.2.1.a", "vii", "vii. El establecimiento tiene identificados los alimentos que tienen carácter de alérgenos y dicha información está expresada claramente en las etiquetas de los mismos, para conocimiento de los consumidores.", "C", "C365"),
        new("5.2.1.a", "viii", "viii. El establecimiento  tiene implementado controles para prevenir la contaminación cruzada entre alimentos que contienen alérgenos y otros alimentos que no lo contienen.", "C", "C368"),
        new("5.2.1.a", "ix", "ix. Cuando existe riesgo de que los alimentos que no contienen alérgenos pueden contener trazas de los mismos, se declara en la etiqueta para el conocimiento de los consumidores.", "C", "C371"),
        new("5.2.2.a", "i", "i. Se realizan inspecciones visuales de las materias primas (deterioro, fecha de vencimiento, alérgenos declarados, etc) , o se hacen mediciones de temperatura (para productos refrigerados o cangelados), para tomas las medidas adecuadas antes de la elaboración", null, "C375"),
        new("5.2.2.a", "ii", "ii. Cuando corresponda, se realizan pruebas de laboratorio para comprobar la inocuidad e idoneidad de las materias primas o ingredientes.", null, "C379"),
        new("5.2.2.a", "iii", "iii. Existe documentación y registro sobre las informaciones relevantes de los certificados de análisis, información del proveedor, fecha de recepción, cantidades,  etc.", null, "C382"),
        new("5.2.3.a", "i", "i. El diseño y el material del envasado permite el etiquetado adecuando del alimento.", null, "C386"),
        new("5.2.3.a", "ii", "ii. Cuando se utilicen gases para el envasado, se cuenta con la evidencia documental sobre la inocuidad de dichos materiales.", null, "C388"),
        new("5.2.3.a", "iii", "iii. El material de envasado reutilizable tiene una duración adecuada, es fácil de limpiar y, en caso necesario, de desinfectar.", null, "C390"),
        new("5.3.a", "i", "i. El establecimiento mantiene el control y registro de la potabilidad del agua.", "C", "B394"),
        new("5.3.a", "ii", "ii. El agua y hielo utilizados para la elaboradión de los alimentos son potables.", "C", "B395"),
        new("5.3.a", "iii", "iii. El agua y el hielo se almacenan y manipulan de manera que no se contaminen.", "C", "B396"),
        new("5.3.a", "iv", "iv. La generación de vapor que entra en contacto con los alimentos no da lugar a su contaminación.", "C", "B398"),
        new("5.3.a", "v", "v. El agua que no es apta para el uso en contacto con los alimentos tiene un sistema separado que no contamina el sistema de agua potable.", "M", "B400"),
        new("5.3.a", "vi", "vi. El agua recirculada para su reutilización y el agua recuperada de las operaciones de elaboración de alimentos por evaporación o por filtración, se trata para asegurar que  no comprometa la inocuidad e idoneidad de los alimentos.", "M", "B402"),
        new("5.4.a", "i", "i. Los procedimientos permiten la rápida y eficaz identificación y el retiro completo del mercado de cualquier alimento que pueda suponer un riesgo para la salud pública.", "M", "C409"),
        new("5.4.a", "ii", "ii. Los procedimientos permiten la devolución por parte de los consumidores de cualquier alimento que pueda suponer un riesgo para la salud pública.", "m", "C412"),
        new("5.4.a", "iii", "iii. Los procedimientos contemplan evaluar los demás lotes de productos elaborados en condiciones similares a los  que se han retirado del mercado para determinar si son inocuos y seguros.", "m", "C415"),
        new("5.4.a", "iv", "iv. Los procedimientos permiten informar a la autoridad competente y emitir alertas públicas cuando el producto pueda haber llegado a los consumidores y sea necesario su devolución o retiro del mercado.", "M", "C418"),
        new("5.4.a", "v", "v. Los procedimientos para retirar alimentos del mercado se revisan y actualizan cuando sea necesario, a partir de los resultados de simulacros periódicos.", "m", "C421"),
        new("5.4.a", "vi", "vi. El establecimiento conserva la documentación escrita con la información de la causa y el alcance de un retiro del mercado y las medidas correctivas adoptadas.", "m", "C424"),
        new("5.4.b", "i", "i. Se almacenan hasta que se destruyan", null, "C428"),
        new("5.4.b", "ii", "ii. Se mantienen almacenados hasta que se utilicen con fines distintos del consumo humano", null, "C429"),
        new("5.4.b", "iii", "iii. Se mantienen almacenados hasta que se determine su inocuidad para el consumo humano", null, "C431"),
        new("5.4.b", "iv", "iv. Se mantienen almacenados hasta que se reelaboren de manera que se reduzca el peligro a niveles aceptables y la autoridad competente lo permita", null, "C433"),
        new("6.1.a", "i", "i. Las etiquetas muestran el Nombre de los productos", "m", "B438"),
        new("6.1.a", "ii", "ii. Las etiquetas muestran la lista de Ingredientes", "C", "B439"),
        new("6.1.a", "iii", "iii. Las etiquetas muestran el contenido neto y peso escurrido", "m", "B440"),
        new("6.1.a", "iv", "iv. Las etiquetas muestran el nombre y dirección del fabricante", "m", "B441"),
        new("6.1.a", "v", "v Las etiquetas muestran el Registros Sanitario", "M", "B442"),
        new("6.1.a", "vi", "vi. Las etiquetas muestran el país de origen", "m", "B443"),
        new("6.1.a", "vii", "vii. Las etiquetas muestran la identificación del lote", "M", "B444"),
        new("6.1.a", "viii", "viii. Las etiquetas muestran la fecha de vencimiento", "m", "B445"),
        new("6.1.a", "ix", "ix. Las etiquetas muestran las instrucciones para la conservación", "M", "B446"),
        new("6.1.a", "x", "x. Las etiquetas muestran las instrucciones para el uso", "M", "B447"),
        new("6.1.a", "xi", "xi. Las etiquetas muestran la declaración de alérgenos", "C", "B448"),
        new("7.a", "i", "i. Los medios de transporte están diseñados de tal manera que permiten una separación eficaz entre los distintos alimentos y/o entre otros alimentos y los articulos no alimentarios que podrian causar contaminación.", null, "B452"),
        new("7.a", "ii", "ii. Ofrecen  una protección eficaz contra la contaminación, incluidos el polvo y el humo.", null, "B455"),
        new("7.a", "iii", "iii. Los medios de transporte se mantienen en un estado adecuado de limpieza, reparación y mantenimiento.", null, "B457"),
        new("7.a", "iv", "iv. Cuando el medio de transporte se utiliza para transportar diferentes tipos de alimentos o productos no alimentarios, están definidos los controles de limpieza, desinfección y secado entre cada carga.", null, "B459"),
        new("7.a", "v", "v. Las operaciones de carga y descarga deben realizarse fuera de las áreas de producción.", null, "B462"),
        new("7.a", "vi", "vi. Se mantienen los registros de las actividades de limpieza y desinfección de los medios de tranporte.", null, "B464"),
        new("7.a", "vii", "vii. El personal que realiza el transporte está capacitado en la adecuada manipulación de los alimentos que transporta y en las medidas precautorias para asegurar su inocuidad.", null, "B466")
    ];
}
